// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFolderExists(arg1, arg2) {
  return window['go']['main']['App']['CheckFolderExists'](arg1, arg2);
}

export function CheckFoldersExist(arg1, arg2) {
  return window['go']['main']['App']['CheckFoldersExist'](arg1, arg2);
}

export function CheckGifsFolderExists(arg1, arg2) {
  return window['go']['main']['App']['CheckGifsFolderExists'](arg1, arg2);
}

export function CheckGifsFolderHasMP4(arg1, arg2) {
  return window['go']['main']['App']['CheckGifsFolderHasMP4'](arg1, arg2);
}

export function CleanupExtractorProcesses() {
  return window['go']['main']['App']['CleanupExtractorProcesses']();
}

export function ClearAllAccountsFromDB() {
  return window['go']['main']['App']['ClearAllAccountsFromDB']();
}

export function ClearStoredAuthToken(arg1) {
  return window['go']['main']['App']['ClearStoredAuthToken'](arg1);
}

export function ConvertGIFs(arg1) {
  return window['go']['main']['App']['ConvertGIFs'](arg1);
}

export function DeleteAccountFromDB(arg1) {
  return window['go']['main']['App']['DeleteAccountFromDB'](arg1);
}

export function DownloadExifTool() {
  return window['go']['main']['App']['DownloadExifTool']();
}

export function DownloadExtractor() {
  return window['go']['main']['App']['DownloadExtractor']();
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function DownloadMedia(arg1) {
  return window['go']['main']['App']['DownloadMedia'](arg1);
}

export function DownloadMediaWithMetadata(arg1) {
  return window['go']['main']['App']['DownloadMediaWithMetadata'](arg1);
}

export function DownloadProfileImage(arg1) {
  return window['go']['main']['App']['DownloadProfileImage'](arg1);
}

export function ExportAccountJSON(arg1, arg2) {
  return window['go']['main']['App']['ExportAccountJSON'](arg1, arg2);
}

export function ExportAccountsTXT(arg1, arg2) {
  return window['go']['main']['App']['ExportAccountsTXT'](arg1, arg2);
}

export function ExportFailedLogs(arg1) {
  return window['go']['main']['App']['ExportFailedLogs'](arg1);
}

export function ExtractDateRange(arg1) {
  return window['go']['main']['App']['ExtractDateRange'](arg1);
}

export function ExtractTimeline(arg1) {
  return window['go']['main']['App']['ExtractTimeline'](arg1);
}

export function GetAccountFromDB(arg1) {
  return window['go']['main']['App']['GetAccountFromDB'](arg1);
}

export function GetAllAccountsFromDB() {
  return window['go']['main']['App']['GetAllAccountsFromDB']();
}

export function GetAllGroups() {
  return window['go']['main']['App']['GetAllGroups']();
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function GetExifToolVersionStatus() {
  return window['go']['main']['App']['GetExifToolVersionStatus']();
}

export function GetExtractorVersionStatus() {
  return window['go']['main']['App']['GetExtractorVersionStatus']();
}

export function GetFFmpegVersionStatus() {
  return window['go']['main']['App']['GetFFmpegVersionStatus']();
}

export function GetFolderPath(arg1, arg2) {
  return window['go']['main']['App']['GetFolderPath'](arg1, arg2);
}

export function GetGifsFolderPath(arg1, arg2) {
  return window['go']['main']['App']['GetGifsFolderPath'](arg1, arg2);
}

export function GetSavedAccountFromDB(arg1, arg2) {
  return window['go']['main']['App']['GetSavedAccountFromDB'](arg1, arg2);
}

export function GetStoredAuthToken(arg1) {
  return window['go']['main']['App']['GetStoredAuthToken'](arg1);
}

export function ImportAccountFromJSON() {
  return window['go']['main']['App']['ImportAccountFromJSON']();
}

export function IsExifToolInstalled() {
  return window['go']['main']['App']['IsExifToolInstalled']();
}

export function IsExtractorInstalled() {
  return window['go']['main']['App']['IsExtractorInstalled']();
}

export function IsFFmpegInstalled() {
  return window['go']['main']['App']['IsFFmpegInstalled']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveAccountToDB(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveAccountToDB'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveAccountToDBWithStatus(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveAccountToDBWithStatus'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SetStoredAuthToken(arg1, arg2) {
  return window['go']['main']['App']['SetStoredAuthToken'](arg1, arg2);
}

export function StopDownload() {
  return window['go']['main']['App']['StopDownload']();
}

export function UpdateAccountGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAccountGroup'](arg1, arg2, arg3);
}
