// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function CheckFolderExists(arg1:string,arg2:string):Promise<boolean>;

export function CheckFoldersExist(arg1:string,arg2:Array<string>):Promise<Record<string, boolean>>;

export function CheckGifsFolderExists(arg1:string,arg2:string):Promise<boolean>;

export function CheckGifsFolderHasMP4(arg1:string,arg2:string):Promise<boolean>;

export function CleanupExtractorProcesses():Promise<void>;

export function ClearAllAccountsFromDB():Promise<void>;

export function ClearStoredAuthToken(arg1:string):Promise<void>;

export function ConvertGIFs(arg1:main.ConvertGIFsRequest):Promise<main.ConvertGIFsResponse>;

export function DeleteAccountFromDB(arg1:number):Promise<void>;

export function DownloadExifTool():Promise<void>;

export function DownloadExtractor():Promise<void>;

export function DownloadFFmpeg():Promise<void>;

export function DownloadMedia(arg1:main.DownloadMediaRequest):Promise<main.DownloadMediaResponse>;

export function DownloadMediaWithMetadata(arg1:main.DownloadMediaWithMetadataRequest):Promise<main.DownloadMediaResponse>;

export function DownloadProfileImage(arg1:main.DownloadProfileImageRequest):Promise<string>;

export function ExportAccountJSON(arg1:number,arg2:string):Promise<string>;

export function ExportAccountsTXT(arg1:Array<number>,arg2:string):Promise<string>;

export function ExportFailedLogs(arg1:string):Promise<string>;

export function ExtractDateRange(arg1:main.DateRangeRequest):Promise<string>;

export function ExtractTimeline(arg1:main.TimelineRequest):Promise<string>;

export function GetAccountFromDB(arg1:number):Promise<string>;

export function GetAllAccountsFromDB():Promise<Array<backend.AccountListItem>>;

export function GetAllGroups():Promise<Array<Record<string, string>>>;

export function GetDefaults():Promise<Record<string, string>>;

export function GetExifToolVersionStatus():Promise<backend.DependencyVersionStatus>;

export function GetExtractorVersionStatus():Promise<backend.ExtractorVersionStatus>;

export function GetFFmpegVersionStatus():Promise<backend.DependencyVersionStatus>;

export function GetFolderPath(arg1:string,arg2:string):Promise<string>;

export function GetGifsFolderPath(arg1:string,arg2:string):Promise<string>;

export function GetSavedAccountFromDB(arg1:string,arg2:string):Promise<string>;

export function GetStoredAuthToken(arg1:string):Promise<string>;

export function ImportAccountFromJSON():Promise<main.ImportAccountResponse>;

export function IsExifToolInstalled():Promise<boolean>;

export function IsExtractorInstalled():Promise<boolean>;

export function IsFFmpegInstalled():Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function SaveAccountToDB(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<void>;

export function SaveAccountToDBWithStatus(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:boolean):Promise<void>;

export function SelectFolder(arg1:string):Promise<string>;

export function SetStoredAuthToken(arg1:string,arg2:string):Promise<void>;

export function StopDownload():Promise<boolean>;

export function UpdateAccountGroup(arg1:number,arg2:string,arg3:string):Promise<void>;
